export const LEAD_INTERESTS = {
  training: [
    "Front End Development Foundation",
    "Back End Development",
    "Full Stack Development",
    "Video Editing",
    "AutoCAD (2D & 3D)",
    "Wordpress Web Design",
    "Android App Development",
    "VFX & ANIMATION",
    "Graphics & Visual Designing",
    "Adobe Photoshop",
    "CorelDraw",
    "Digital marketing",
    "Adobe Illustrator",
    "3D INTERIOR EXTERIOR DESIGN",
  ],
  service: [
    "Website Development",
    "Android & iOS App Development",
    "Graphic Designing",
    "Branding & Brand Promotion",
    "Digital Marketing",
    "VFX & Animation",
    "CRM Solutions",
    "Cloud Solutions",
    "Marketing Tools & Automation",
    "Content Creation & Copywriting",
    "UI/UX Design",
    "Social Media Management",
    "E-commerce Development & Management",
    "Performance Marketing",
    "Influencer Marketing",
    "Photography & Videography",
    "Public Relations (PR)",
    "Bulk Marketing (Highlighted Service)",
  ],
  internship: [
    "Front End (React.js)",
    "Back End (Node.js)",
    "Full Stack",
  ],
};
