// Mock data for the IT Employee Dashboard (frontend-only, no backend calls)

export const employee = {
  name: "Ganesh",
  fullName: "Ganesh Sharma",
  role: "Web Developer",
  department: "IT Department (Aajmer HQ)",
  crmId: "6a9a5bd5a31c3df9a2af53cd",
  branch: "Aajmer",
  designation: "Web Developer",
  dept: "IT",
  email: "ganesh.dev@itcrm.corp",
  phone: "+91 98765 43210",
  status: "Active Employee",
};

export const dashboardStats = {
  pendingTasks: { total: 4, highPriority: 2, dueToday: 2 },
  teamTasks: { total: 18, inProgress: 12, completedThisWeek: 6 },
  attendance: { status: "Present", time: "09:15 AM", note: "Punched in via Aajmer Office" },
  leaveBalance: { days: 14, note: "Casual & Medical Leave" },
};

export const assignedTasks = [
  {
    id: 1,
    title: "Fix CRM Authentication Bug",
    priority: "High",
    description: "Resolve session token expiration issue for Aajmer branch",
    status: "In Progress",
    due: "Today",
  },
  {
    id: 2,
    title: "Deploy staging API updates",
    priority: "Medium",
    description: "Push v2.4 endpoints to staging cluster for testing",
    status: "Pending Review",
    due: "Tomorrow",
  },
  {
    id: 3,
    title: "Update SSL certificate for Aajmer server",
    priority: "High",
    description: "Domain wildcard renewal before expiry on Friday",
    status: "In Progress",
    due: "Oct 26",
  },
  {
    id: 4,
    title: "Optimize database queries",
    priority: "Normal",
    description: "Add indexes on attendance log timestamps",
    status: "To Do",
    due: "Oct 28",
  },
];

export const teamOverview = [
  {
    id: 1,
    title: "Server Migration (AWS eu-west)",
    lead: "Rajesh Kumar • DevOps",
    status: "75% Done",
  },
  {
    id: 2,
    title: "Employee Biometric Sync Service",
    lead: "Sunita Roy • Backend",
    status: "Testing",
  },
  {
    id: 3,
    title: "Firewall Rule Audit Q4",
    lead: "Amit Verma • Security",
    status: "Completed",
  },
];

export const attendanceLogs = [
  {
    id: 1,
    date: "Tue, Oct 24, 2023",
    today: true,
    shift: "09:30 AM – 06:30 PM",
    punchIn: "09:15 AM",
    punchInNote: "On-Time (Bio #02)",
    punchOut: "In Progress",
    workHours: "04h 35m",
    workHoursNote: "Target: 08h 30m",
    breakTime: "45m (Lunch)",
    location: "Office (Aajmer HQ)",
    status: "Present (Active)",
    action: "Log Break",
  },
  {
    id: 2,
    date: "Mon, Oct 23, 2023",
    shift: "09:30 AM – 06:30 PM",
    punchIn: "09:20 AM",
    punchInNote: "On-Time",
    punchOut: "06:45 PM",
    punchOutNote: "+15m Overtime",
    workHours: "09h 25m",
    breakTime: "50m",
    location: "Office (Aajmer HQ)",
    status: "Present",
    action: "View Logs",
  },
  {
    id: 3,
    date: "Sat, Oct 21, 2023",
    shift: "09:30 AM – 06:30 PM",
    punchIn: "09:28 AM",
    punchInNote: "On-Time",
    punchOut: "06:30 PM",
    workHours: "09h 02m",
    breakTime: "45m",
    location: "Office (Aajmer HQ)",
    status: "Present",
    action: "View Logs",
  },
  {
    id: 4,
    date: "Fri, Oct 20, 2023",
    shift: "09:30 AM – 06:30 PM",
    punchIn: "09:12 AM",
    punchInNote: "Early Punch",
    punchOut: "06:35 PM",
    workHours: "09h 23m",
    breakTime: "45m",
    location: "Office (Aajmer HQ)",
    status: "Present",
    action: "View Logs",
  },
];

export const allTasks = [
  {
    id: "TCK-2849",
    title: "Optimize attendance geofence radius sync on Aajmer branch terminal",
    tags: ["Biometric API", "Sprint 24 • Bugfix"],
    assignee: "Ganesh Sharma",
    priority: "Critical",
    due: "Today 05:00 PM",
    dueNote: "Under SLA limit",
    logged: "14h",
    total: "18h",
    progress: 78,
    status: "In Progress",
  },
  {
    id: "TCK-2845",
    title: "Implement responsive layout enhancements for CRM Department View",
    tags: ["Frontend • Polish"],
    assignee: "Ganesh Sharma",
    priority: "High",
    due: "Tomorrow, 02:00 PM",
    dueNote: "SLA: On track",
    logged: "11h",
    total: "16h",
    progress: 69,
    status: "In Progress",
  },
  {
    id: "TCK-2835",
    title: "Restyle 'Mark Attendance' card interface and input dropdown styling",
    tags: ["UI/UX Polish"],
    assignee: "Ganesh Sharma",
    priority: "Low",
    due: "Completed Oct 25",
    dueNote: "Closed by lead",
    logged: "12h",
    total: "12h",
    progress: 100,
    status: "Completed",
  },
  {
    id: "TCK-2822",
    title: "Fix table scroll sync & pagination layout in Attendance Report view",
    tags: ["Frontend • Bugfix"],
    assignee: "Ganesh Sharma",
    priority: "High",
    due: "Oct 30, 2026",
    dueNote: "In Review Queue",
    logged: "8h",
    total: "8h",
    progress: 100,
    status: "Under Review",
  },
  {
    id: "TCK-2818",
    title: "Build client-side form validation hooks for Leave Request submission",
    tags: ["Payroll API", "Form UX"],
    assignee: "Ganesh Sharma",
    priority: "Medium",
    due: "Nov 01, 2026",
    dueNote: "PR pending",
    logged: "6h",
    total: "6h",
    progress: 100,
    status: "Under Review",
  },
];

export const leaveBalances = {
  casual: { left: 6, used: 6, total: 12 },
  sick: { left: 8, used: 2, total: 10 },
  earned: { accrued: 14, note: "Accrued yearly • Carry forward valid" },
  pending: { count: 1, note: "Under Review with Lead & HR" },
};

export const leaveHistory = [
  {
    id: "LV-8941",
    type: "Casual Leave",
    dates: "Nov 12 - Nov 13, 2026",
    duration: "2 Working Days (Full Day)",
    reason: "Family event at Jaipur and travel obligations.",
    reliever: "Rahul Verma",
    appliedOn: "Nov 01, 2026",
    status: "Under Review",
  },
  {
    id: "LV-8720",
    type: "Sick Leave",
    dates: "Oct 14, 2026",
    duration: "1 Working Day",
    reason: "Viral fever & medical rest with doctor note.",
    reliever: "Priya Patel",
    appliedOn: "Oct 14, 2026",
    status: "Approved",
  },
  {
    id: "LV-8512",
    type: "Casual Leave",
    dates: "Sep 22 - Sep 23, 2026",
    duration: "2 Working Days",
    reason: "Personal errand and home maintenance visit.",
    reliever: "Rahul Verma",
    appliedOn: "Sep 18, 2026",
    status: "Approved",
  },
  {
    id: "LV-8104",
    type: "Comp-Off",
    dates: "Aug 30, 2026",
    duration: "1 Working Day",
    reason: "Overtime for DB server migration on Saturday.",
    reliever: "Devendra Rao",
    appliedOn: "Aug 28, 2026",
    status: "Approved",
  },
];
