import React, { useEffect, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import { MessageCircleQuestion, Clock3, CircleCheck, Archive, Plus, Search, ArrowLeft, Paperclip, X, Send, History } from 'lucide-react';
import { CLARIFICATION_STATUSES as STATUSES, CLARIFICATION_PEOPLE as PEOPLE, CLARIFICATION_PRIORITIES as PRIORITIES, EMPTY_FILTERS, createClarifications, filterClarifications, updateClarification } from './clarificationData.js';
import './ClarificationPage.css';
import { useSupportRecords } from './supportStore.js';
const token=value=>value.toLowerCase().replaceAll(' ','-');
const timestamp=value=>new Date(value).toLocaleString('en-IN',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'});
const dateLabel=value=>new Date(value).toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'});
function Tag({value}) {return <span className={`clar-tag clar-${token(value)}`}>{value}</span>;}
function Select({label,value,onChange,options,all}) {return <label className="clar-field"><span>{label}</span><select value={value} onChange={e=>onChange(e.target.value)}>{all&&<option value="">{all}</option>}{options.map(option=><option key={option}>{option}</option>)}</select></label>;}
async function attachmentsFrom(files) {
  if(files.length>4||files.some(f=>f.size>2*1024*1024))throw new Error('Choose up to 4 files, each no larger than 2 MB.');
  return Promise.all(files.map(file=>new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve({id:crypto.randomUUID(),name:file.name,url:reader.result});reader.onerror=()=>reject(new Error('Could not read the attachment. Please try again.'));reader.readAsDataURL(file);})));
}
function AskDialog({projects,people,person,onClose,onCreate}) {
  const ref=useRef(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  useEffect(()=>{const previous=document.activeElement;const dialog=ref.current;dialog.showModal();return()=>{dialog.close();previous?.focus();};},[]);
  async function submit(event) {
    event.preventDefault();const form=event.currentTarget;const data=new FormData(form);
    if(!data.get('subject').trim()||!data.get('question').trim()){setError('Enter a subject and question.');return;}
    setBusy(true);setError('');
    try{const at=new Date().toISOString();const attachments=(await attachmentsFrom([...form.elements.files.files])).map(file=>({...file,author:person,at}));
      onCreate({subject:data.get('subject').trim(),question:data.get('question').trim(),project:data.get('project'),assignedTo:data.get('assignedTo'),priority:data.get('priority'),askedBy:person,at,status:'Needs Clarification',attachments,replies:[],activity:[{id:crypto.randomUUID(),text:`${person} asked for clarification.`,at}]});
    }catch(err){setError(err.message);setBusy(false);}
  }
  return createPortal(<dialog ref={ref} className="clar-dialog" aria-labelledby="clar-ask-title" onCancel={event=>{if(busy)event.preventDefault();else onClose();}}><form onSubmit={submit}><header><div><p className="eyebrow">PROJECT COMMUNICATION</p><h2 id="clar-ask-title">Ask for Clarification</h2><p>Give the team enough context to provide a clear answer.</p></div><button type="button" className="icon-button" disabled={busy} aria-label="Close clarification form" onClick={onClose}><X size={20}/></button></header><fieldset disabled={busy}><div className="clar-form-grid">
    <label className="clar-field clar-wide"><span>Subject *</span><input autoFocus name="subject" required maxLength={160} placeholder="What needs clarification?"/></label>
    <label className="clar-field"><span>Project *</span><select name="project" required>{projects.map(p=><option key={p}>{p}</option>)}</select></label><label className="clar-field"><span>Assigned to *</span><select name="assignedTo" required defaultValue={people.find(p=>p!==person)||person}>{people.map(p=><option key={p}>{p}</option>)}</select></label>
    <label className="clar-field"><span>Priority</span><select name="priority" defaultValue="Medium">{PRIORITIES.map(p=><option key={p}>{p}</option>)}</select></label><label className="clar-field"><span>Asked by</span><input value={person} readOnly/></label>
    <label className="clar-field clar-wide"><span>Question *</span><textarea name="question" required maxLength={6000} rows={5} placeholder="Describe the question, relevant context, and the decision you need."/></label><label className="clar-field clar-wide"><span>Attachments</span><input type="file" name="files" multiple/><small>Up to 4 files, 2 MB each.</small></label></div></fieldset>{error&&<p className="clar-error" role="alert">{error}</p>}<footer><button type="button" className="ghost-button" disabled={busy} onClick={onClose}>Cancel</button><button className="primary-button" disabled={busy}>{busy?'Adding�':'Ask for Clarification'}</button></footer></form></dialog>,document.body);
}
export default function ClarificationPage({projects=[],person='Ekta Singh'}) {
  const [items,setItems,storageError]=useSupportRecords('clarifications',person);
  const [filters,setFilters]=useState(EMPTY_FILTERS);const [page,setPage]=useState(1);const [selectedId,setSelectedId]=useState(null);const [asking,setAsking]=useState(false);const [reply,setReply]=useState('');const [notice,setNotice]=useState('');const [error,setError]=useState('');const [uploading,setUploading]=useState(false);const replyRef=useRef(null);const fileRef=useRef(null);
  const projectsList=[...new Set([...projects.map(p=>p.name||p.projectName),...items.map(i=>i.project)])].filter(Boolean).sort();
  const people=[...new Set([...PEOPLE,person,...items.map(i=>i.assignedTo)])];
  const selected=items.find(i=>i.id===selectedId);const filtered=filterClarifications(items,filters);const pages=Math.max(1,Math.ceil(filtered.length/6));const currentPage=Math.min(page,pages);const visible=filtered.slice((currentPage-1)*6,currentPage*6);
  function changeFilter(key,value){setFilters(f=>({...f,[key]:value}));setPage(1);}
  function open(item){setSelectedId(item.id);setReply('');setNotice('');setError('');}
  function act(action){try{const updated=updateClarification(selected,{...action,id:crypto.randomUUID()},person);setItems(list=>list.map(item=>item.id===updated.id?updated:item));setError('');setNotice(action.type==='reply'?'Reply added.':action.type==='attach'?'Attachment added.':`Status updated to ${updated.status}.`);return true;}catch(err){setError(err.message);return false;}}
  async function attach(event){const files=[...event.target.files];event.target.value='';if(!files.length)return;setUploading(true);setError('');try{act({type:'attach',files:await attachmentsFrom(files)});}catch(err){setError(err.message);}finally{setUploading(false);}}
  const stats=[['Pending','Needs Clarification',MessageCircleQuestion,'Questions to review'],['Waiting for Reply','Waiting for Reply',Clock3,'Awaiting a response'],['Answered','Answered',CircleCheck,'Ready to close'],['Closed','Closed',Archive,'Completed discussions']];
  return <div className="clar-page">{notice&&<p className="clar-notice" role="status">{notice}</p>}{storageError&&<p className="clar-error" role="alert">{storageError}</p>}{error&&<p className="clar-error" role="alert">{error}</p>}
    {selected?<><header className="clar-heading"><div><button className="clar-back" disabled={uploading} onClick={()=>{setSelectedId(null);setError('');setNotice('');}}><ArrowLeft size={16}/> All clarifications</button><p className="eyebrow">{selected.id} / {selected.project}</p><h2>{selected.subject}</h2><div className="clar-inline"><Tag value={selected.status}/><Tag value={selected.priority}/></div></div></header>
    <ol className="clar-flow" aria-label="Clarification status flow">{STATUSES.map((status,index)=><li key={status} className={index<=STATUSES.indexOf(selected.status)?'reached':''} aria-current={status===selected.status?'step':undefined}><span>{index+1}</span>{status}</li>)}</ol>
    <div className="clar-detail-grid"><div className="clar-main"><section className="panel clar-section"><h3>Question</h3><p className="clar-prose">{selected.question}</p><div className="clar-meta"><span>Asked by <strong>{selected.askedBy}</strong></span><time>{timestamp(selected.at)}</time></div><div className="clar-attachment-head"><h4><Paperclip size={16}/> Attachments ({selected.attachments.length})</h4>{selected.status!=='Closed'&&<><button className="ghost-button" disabled={uploading} onClick={()=>fileRef.current.click()}><Plus size={15}/>{uploading?'Adding�':'Add Attachment'}</button><input ref={fileRef} className="clar-file-input" type="file" multiple onChange={attach} aria-label="Add clarification attachments"/></>}</div><small className="clar-muted">Up to 4 files per upload, 2 MB each.</small><div className="clar-files">{selected.attachments.length?selected.attachments.map(file=><a key={file.id} href={file.url} download={file.name}><Paperclip size={16}/><div><strong>{file.name}</strong><small>{file.author} � {timestamp(file.at)}</small></div><span>Download</span></a>):<p className="clar-muted">No attachments yet.</p>}</div></section>
    <section className="panel clar-section"><h3>Replies ({selected.replies.length})</h3>{selected.replies.length?selected.replies.map(r=><article className="clar-reply" key={r.id}><div><strong>{r.author}</strong><time>{timestamp(r.at)}</time></div><p>{r.text}</p></article>):<p className="clar-muted">No replies yet. Add context or share an answer below.</p>}{selected.status==='Closed'?<p className="clar-muted">This clarification is closed. Replies and attachments remain available for reference.</p>:<form onSubmit={e=>{e.preventDefault();if(act({type:'reply',text:reply}))setReply('');}}><label className="clar-field"><span>Your reply</span><textarea ref={replyRef} rows={4} maxLength={6000} value={reply} onChange={e=>setReply(e.target.value)} placeholder="Share an answer or ask a follow-up question�"/></label><button className="primary-button" disabled={!reply.trim()||uploading}><Send size={15}/> Post Reply</button></form>}</section></div>
    <aside><section className="panel clar-section"><h3>Clarification details</h3><dl className="clar-facts">{[['Assigned to',selected.assignedTo],['Asked by',selected.askedBy],['Project',selected.project],['Priority',selected.priority],['Created',timestamp(selected.at)]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><div className="clar-actions">{selected.status!=='Closed'&&<button className="ghost-button" disabled={uploading} onClick={()=>replyRef.current.focus()}>Reply</button>}{selected.status==='Needs Clarification'&&<button className="primary-button" disabled={uploading} onClick={()=>act({type:'send'})}>Request Reply</button>}{selected.status==='Waiting for Reply'&&<><button className="primary-button" disabled={!selected.replies.length||uploading} onClick={()=>act({type:'answer'})}>Mark as Answered</button>{!selected.replies.length&&<small>Add a reply before marking as answered.</small>}</>}{selected.status==='Answered'&&<button className="primary-button" disabled={uploading} onClick={()=>act({type:'close'})}>Close Clarification</button>}</div></section>
    <section className="panel clar-section"><h3><History size={17}/> Activity</h3><ol className="clar-activity">{[...selected.activity].reverse().map(a=><li key={a.id}><p>{a.text}</p><time>{timestamp(a.at)}</time></li>)}</ol></section></aside></div></>:<>
    <header className="clar-heading"><div><p className="eyebrow">PROJECT COMMUNICATION</p><h2>Clarification</h2><p>Get clear answers, resolve questions, and keep projects moving.</p></div><button className="primary-button" onClick={()=>setAsking(true)}><Plus size={18}/> Ask for Clarification</button></header>
    <div className="clar-summary">{stats.map(([label,status,Icon,hint])=><article className="panel clar-stat" key={label}><div><span>{label}</span><Icon size={20}/></div><strong>{items.filter(i=>i.status===status).length}</strong><small>{hint}</small></article>)}</div>
    <section className="panel clar-register"><div className="clar-register-head"><div><h3>Clarification requests <span>{items.length}</span></h3><p>Questions and decisions across your projects</p></div><small>Demo � Saved in this browser</small></div><div className="clar-filters"><label className="clar-search"><Search size={18}/><input aria-label="Search clarifications" placeholder="Search ID, subject, project or person�" value={filters.search} onChange={e=>changeFilter('search',e.target.value)}/></label><div className="clar-filter-grid"><Select label="Status" value={filters.status} onChange={v=>changeFilter('status',v)} options={STATUSES} all="All statuses"/><Select label="Priority" value={filters.priority} onChange={v=>changeFilter('priority',v)} options={PRIORITIES} all="All priorities"/><Select label="Project" value={filters.project} onChange={v=>changeFilter('project',v)} options={projectsList} all="All projects"/><Select label="Assigned to" value={filters.assignedTo} onChange={v=>changeFilter('assignedTo',v)} options={people} all="Anyone"/><label className="clar-field"><span>Asked date</span><input type="date" value={filters.date} onChange={e=>changeFilter('date',e.target.value)}/></label><button className="clar-reset" onClick={()=>{setFilters(EMPTY_FILTERS);setPage(1);}}>Clear filters</button></div></div>
    <div className="clar-table-wrap"><table className="clar-table"><thead><tr>{['ID','Subject','Project','Asked By','Assigned To','Date','Priority','Status','Action'].map(label=><th scope="col" key={label}>{label}</th>)}</tr></thead><tbody>{visible.map(item=><tr key={item.id}><td className="clar-id">{item.id}</td><td className="clar-subject"><button onClick={()=>open(item)}>{item.subject}</button></td><td>{item.project}</td><td>{item.askedBy}</td><td>{item.assignedTo}</td><td className="clar-date">{dateLabel(item.at)}</td><td><Tag value={item.priority}/></td><td><Tag value={item.status}/></td><td><button className="clar-view" aria-label={`View ${item.id}`} onClick={()=>open(item)}>View</button></td></tr>)}</tbody></table>{!visible.length&&<div className="clar-empty"><MessageCircleQuestion size={28}/><h3>No matching clarifications</h3><p>Try another keyword or clear the filters.</p><button className="ghost-button" onClick={()=>{setFilters(EMPTY_FILTERS);setPage(1);}}>Clear filters</button></div>}</div>
    <footer className="clar-pagination"><span>{filtered.length?`${(currentPage-1)*6+1}�${Math.min(currentPage*6,filtered.length)}`:'0'} of {filtered.length} clarifications</span><nav aria-label="Clarification pages"><button disabled={currentPage===1} onClick={()=>setPage(currentPage-1)}>Previous</button><span>{currentPage} / {pages}</span><button disabled={currentPage===pages} onClick={()=>setPage(currentPage+1)}>Next</button></nav></footer></section></>}
    {asking&&<AskDialog projects={projectsList} people={people} person={person} onClose={()=>setAsking(false)} onCreate={item=>{const id=`CLR-${Math.max(108,...items.map(i=>Number(i.id.replace('CLR-',''))||0))+1}`;const record={...item,id};setItems(list=>[record,...list]);setAsking(false);open(record);setNotice(`${id} created. Request a reply to move it to Waiting for Reply.`);}}/>}
  </div>;
}
