import React, { useEffect, useState } from 'react';
import { FolderKanban, CircleCheck, ClipboardList, Clock3, Bug, MessageCircleQuestion, ArrowUpRight, AlertCircle, History, CalendarDays } from 'lucide-react';
import { useSupportRecords } from './supportStore.js';
import { dailyOverview } from './dailyOverview.js';
import './DailyOverview.css';
const dateLabel=date=>date?date.toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'}):'No deadline set';
const timeLabel=at=>new Date(at).toLocaleString('en-IN',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'});
function Header({title,subtitle,onView}) {return <div className="daily-panel-head"><div><h3>{title}</h3>{subtitle&&<p>{subtitle}</p>}</div>{onView&&<button className="daily-link" onClick={onView}>View All <ArrowUpRight size={14}/></button>}</div>;}
export default function DailyOverview({projects,person,onNavigate,onProject}) {
  const [bugs]=useSupportRecords('bugs',person);
  const [clarifications]=useSupportRecords('clarifications',person);
  const [now,setNow]=useState(()=>new Date());
  const [allActivity,setAllActivity]=useState(false);const [allAttention,setAllAttention]=useState(false);
  useEffect(()=>{const timer=setInterval(()=>setNow(new Date()),60000);return()=>clearInterval(timer);},[]);
  const data=dailyOverview(projects,bugs,clarifications,now);
  const today=new Date(now);today.setHours(0,0,0,0);
  const cards=[['Active Projects',data.active.length,'active-projects',FolderKanban],['Completed Projects',data.completed.length,'completed-projects',CircleCheck],['Pending Tasks',data.pending.length,'my-work',ClipboardList],['Overdue Tasks',data.overdue.length,'my-work',Clock3],['Open Bugs',data.openBugs.length,'open-bugs',Bug],['Clarifications',data.unanswered.length,'clarification',MessageCircleQuestion]];
  const go=entry=>entry.project?onProject(entry.project):onNavigate(entry.page);
  return <div className="daily-overview"><div className="daily-heading"><div><p className="eyebrow">DAILY OVERVIEW</p><h2>Your work at a glance</h2></div><span><CalendarDays size={16}/>{dateLabel(now)}</span></div>
    <div className="daily-stats">{cards.map(([label,count,page,Icon])=><button key={label} className={`panel daily-stat ${label==='Overdue Tasks'&&count?'daily-stat-alert':''}`} onClick={()=>onNavigate(page)}><div><Icon size={19}/><ArrowUpRight size={14}/></div><strong>{count}</strong><span>{label}</span><small>{label==='Pending Tasks'?'Includes overdue tasks':page==='open-bugs'?'Open and in progress':page==='clarification'?'Pending and waiting for reply':'View details'}</small></button>)}</div>
    <div className="daily-columns"><section className="panel"><Header title="My Work" subtitle="Pending tasks, ordered by deadline" onView={()=>onNavigate('my-work')}/><div className="daily-list">{data.pending.slice(0,5).map(task=><button key={task.key} className="daily-work-row" onClick={()=>onNavigate('my-work')}><span className="daily-item-icon"><ClipboardList size={18}/></span><span className="daily-item-copy"><strong>{task.title||task.name}</strong><small>{task.project.name||task.project.projectName}</small><span>{dateLabel(task.deadline)}</span></span><span className={`daily-chip ${task.deadline&&task.deadline<today?'daily-danger':''}`}>{task.deadline&&task.deadline<today?'Overdue':task.status||'Pending'}</span></button>)}{!data.pending.length&&<p className="daily-empty">No pending tasks. You�re all caught up.</p>}</div></section>
    <section className="panel"><Header title="Attention Required" subtitle="Overdue work, priority bugs and deadlines within 7 days"/><div className="daily-list">{(allAttention?data.attention:data.attention.slice(0,5)).map(item=><button key={item.id} className="daily-attention-row" onClick={()=>go(item)}><AlertCircle size={18} className={item.level==='urgent'?'daily-danger-text':''}/><span className="daily-item-copy"><strong>{item.title}</strong><small>{item.detail}{item.deadline?` � ${dateLabel(item.deadline)}`:''}</small></span><ArrowUpRight size={15}/></button>)}{!data.attention.length&&<p className="daily-empty">No urgent issues or upcoming project deadlines.</p>}</div>{data.attention.length>5&&<button className="daily-expand" aria-expanded={allAttention} onClick={()=>setAllAttention(value=>!value)}>{allAttention?'Show less':`View All (${data.attention.length})`}</button>}</section></div>
    <section className="panel"><Header title="Project Overview" subtitle="Progress and delivery dates for active projects" onView={()=>onNavigate('active-projects')}/><div className="daily-project-table"><table><thead><tr><th scope="col">Project</th><th scope="col">Progress</th><th scope="col">Tasks</th><th scope="col">Deadline</th><th scope="col">Status</th><th scope="col">Action</th></tr></thead><tbody>{data.projectRows.slice(0,5).map(row=><tr key={row.project.id}><td><strong>{row.project.name||row.project.projectName}</strong><small>{row.project.client}</small></td><td><div className="daily-progress"><progress value={row.progress} max="100" aria-label={`${row.project.name||row.project.projectName} progress`}/><span>{row.progress}%</span></div></td><td>{row.completedTasks}/{row.totalTasks}</td><td className={row.deadline&&row.deadline<today?'daily-danger-text':''}>{dateLabel(row.deadline)}</td><td><span className="daily-chip">{row.status}</span></td><td><button className="daily-link" aria-label={`View ${row.project.name||row.project.projectName}`} onClick={()=>onProject(row.project)}>View <ArrowUpRight size={14}/></button></td></tr>)}</tbody></table>{!data.projectRows.length&&<p className="daily-empty">No active projects. Completed work is available in Completed Projects.</p>}</div></section>
    <div className="daily-columns"><section className="panel"><Header title="IT Support Overview" subtitle="Live totals from bugs and clarification requests"/><div className="daily-support"><div className="daily-support-block"><div><h4><Bug size={18}/> Bugs</h4><button className="daily-link" onClick={()=>onNavigate('open-bugs')}>View All <ArrowUpRight size={14}/></button></div><div className="daily-support-counts"><span><strong>{data.openBugs.length}</strong>Unresolved</span><span><strong className="daily-danger-text">{data.openBugs.filter(b=>['Critical','High'].includes(b.priority)).length}</strong>High / Critical</span><span><strong>{bugs.filter(b=>b.status==='Resolved').length}</strong>Resolved</span></div><p>{bugs.filter(b=>b.status==='In Progress').length} bugs currently in progress</p></div><div className="daily-support-block"><div><h4><MessageCircleQuestion size={18}/> Clarifications</h4><button className="daily-link" onClick={()=>onNavigate('clarification')}>View All <ArrowUpRight size={14}/></button></div><div className="daily-support-counts"><span><strong>{clarifications.filter(c=>c.status==='Needs Clarification').length}</strong>Pending</span><span><strong>{clarifications.filter(c=>c.status==='Waiting for Reply').length}</strong>Waiting for reply</span><span><strong>{clarifications.filter(c=>c.status==='Answered').length}</strong>Answered</span></div><p>{clarifications.filter(c=>c.status==='Closed').length} discussions closed</p></div></div></section>
    <section className="panel"><Header title="Recent Activity" subtitle="Latest project and support updates"/><ol className="daily-timeline">{(allActivity?data.activity:data.activity.slice(0,6)).map(entry=><li key={entry.id}><span className="daily-timeline-dot"><History size={13}/></span><button onClick={()=>go(entry)}><strong>{entry.text}</strong><span>{entry.detail}</span><time dateTime={entry.at}>{timeLabel(entry.at)}</time></button></li>)}</ol>{!data.activity.length&&<p className="daily-empty">Project status changes, replies and bug updates will appear here.</p>}{data.activity.length>6&&<button className="daily-expand" aria-expanded={allActivity} onClick={()=>setAllActivity(value=>!value)}>{allActivity?'Show less':`View All (${data.activity.length})`}</button>}</section></div>
  </div>;
}
