import React, { useEffect, useState } from 'react';
import { CalendarDays, Clock3, AlertCircle, FolderKanban, ArrowUpRight, History } from 'lucide-react';
import { useSupportRecords } from './supportStore.js';
import { personalWork } from './personalWork.js';
import './DailyOverview.css';
import './MyWorkPage.css';
const dateLabel = date => date ? date.toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'}) : 'No deadline set';
function Section({title,subtitle,children}) {return <section className="panel"><div className="daily-panel-head"><div><h3>{title}</h3><p>{subtitle}</p></div></div>{children}</section>;}
export default function MyWorkPage({projects,person,onProject,onNavigate}) {
  const [bugs]=useSupportRecords('bugs',person);const [questions]=useSupportRecords('clarifications',person);
  const [now,setNow]=useState(()=>new Date());const [showAll,setShowAll]=useState(false);
  useEffect(()=>{const timer=setInterval(()=>setNow(new Date()),60000);return()=>clearInterval(timer);},[]);
  const work=personalWork(projects,bugs,questions,person,now);
  const today=new Date(now);today.setHours(0,0,0,0);
  const action=item=>item.project?onProject(item.project):onNavigate(item.page);
  const rows=(items,empty)=><div className="my-work-list">{items.length?items.map(item=><article className="my-work-row" key={item.id}><span className="daily-item-copy"><strong>{item.title}</strong><small className={item.urgent?'daily-danger-text':''}>{item.reason}</small>{item.deadline&&<span>{dateLabel(item.deadline)}</span>}</span><div className="my-work-actions">{item.project&&<button className="daily-link" onClick={()=>onProject(item.project)}>View Project <ArrowUpRight size={14}/></button>}{item.page&&<button className="daily-link" onClick={()=>onNavigate(item.page)}>{item.page==='open-bugs'?'View Bugs':'View Clarification'} <ArrowUpRight size={14}/></button>}</div></article>):<p className="daily-empty">{empty}</p>}</div>;
  return <div className="daily-overview my-work-page"><div className="daily-heading"><div><p className="eyebrow">PERSONAL WORK OVERVIEW</p><h2>My Work</h2><p className="my-work-intro">Your delivery commitments, project progress, and items needing attention.</p></div><span><CalendarDays size={16}/>{dateLabel(now)}</span></div>
    <div className="my-work-summary">{[['Ongoing Projects',work.active.length,FolderKanban],['Overdue Projects',work.overdueProjects.length,AlertCircle],['Due Within 7 Days',work.approaching.length,CalendarDays],['Delayed / On Hold',work.delayed.length,Clock3]].map(([label,count,Icon])=><article className="panel daily-stat" key={label}><div><Icon size={19}/></div><strong className={label==='Overdue Projects'&&count?'daily-danger-text':''}>{count}</strong><span>{label}</span></article>)}</div>
    <div className="daily-columns"><Section title="Deadlines" subtitle="Active project delivery dates, earliest first"><div className="my-work-list">{work.deadlines.length?work.deadlines.map(row=><article className="my-work-row" key={row.project.id}><span className="daily-item-copy"><strong>{row.project.name}</strong><small>{dateLabel(row.deadline)}</small><span className={row.deadline<today?'daily-danger-text':''}>{row.deadline<today?'Overdue':row.deadline.getTime()===today.getTime()?'Due today':work.approaching.includes(row)?'Approaching deadline':'Upcoming deadline'}</span></span><button className="daily-link" onClick={()=>onProject(row.project)}>View Project <ArrowUpRight size={14}/></button></article>):<p className="daily-empty">No active project deadlines are set.</p>}</div></Section>
    <Section title="Attention Required" subtitle="Delayed delivery, priority bugs assigned to you, and open questions">{rows(work.attention,'No urgent items or unanswered clarifications.')}</Section></div>
    <Section title="Project Progress" subtitle="Delivery progress and current status across your ongoing projects"><div className="daily-project-table"><table><thead><tr>{['Project','Progress','Deadline','Status','Action'].map(label=><th scope="col" key={label}>{label}</th>)}</tr></thead><tbody>{work.projectRows.map(row=><tr key={row.project.id}><td><strong>{row.project.name}</strong><small>{row.project.client}</small></td><td><div className="daily-progress"><progress max="100" value={row.progress} aria-label={`${row.project.name} progress`}/><span>{row.progress}%</span></div></td><td>{dateLabel(row.deadline)}</td><td><span className="daily-chip">{row.status}</span>{work.delayed.includes(row)&&<small className="daily-danger-text">{row.status==='On Hold'?'On hold':'Delayed work'}</small>}</td><td><button className="daily-link" onClick={()=>onProject(row.project)}>View Project <ArrowUpRight size={14}/></button></td></tr>)}</tbody></table>{!work.projectRows.length&&<p className="daily-empty">No ongoing projects. New assignments will appear in Upcoming Work.</p>}</div></Section>
    <div className="daily-columns"><Section title="Upcoming Work" subtitle="New assignments and upcoming project deliveries">{rows(work.upcoming,'No new assignments or upcoming deliveries.')}</Section>
    <Section title="Recent Activity" subtitle="Updates to your projects, assigned bugs, and clarification discussions"><ol className="daily-timeline">{(showAll?work.activity:work.activity.slice(0,6)).map(entry=><li key={entry.id}><span className="daily-timeline-dot"><History size={13}/></span><button onClick={()=>action(entry)}><strong>{entry.text}</strong><span>{entry.detail}</span><time dateTime={entry.at}>{new Date(entry.at).toLocaleString('en-IN',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'})}</time></button></li>)}</ol>{!work.activity.length&&<p className="daily-empty">Your project and support updates will appear here.</p>}{work.activity.length>6&&<button className="daily-expand" aria-expanded={showAll} onClick={()=>setShowAll(value=>!value)}>{showAll?'Show less':'View All Activity'}</button>}</Section></div>
  </div>;
}
