import React, { useEffect, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import { Bug, AlertTriangle, Flag, Clock3, CircleCheck, Search, Plus, X, ArrowLeft, Paperclip, MessageSquare, History, ChevronLeft, ChevronRight } from 'lucide-react';
import { createSampleBugs, filterBugs, STATUSES, PRIORITIES, PEOPLE } from './bugData.js';
import './OpenBugsPage.css';
import { useSupportRecords } from './supportStore.js';

const EMPTY_FILTERS = {search:'',status:'',priority:'',project:'',assignedTo:'',date:''};
const stamp = () => new Date().toISOString();
const dateLabel = value => new Date(value.length === 10 ? `${value}T12:00:00` : value).toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'});
const token = value => value.toLowerCase().replaceAll(' ','-');
function Tag({value}) { return <span className={`bugs-tag bugs-${token(value)}`}>{value}</span>; }
function Select({label,value,onChange,options,all}) { return <label className="bugs-field"><span>{label}</span><select value={value} onChange={e=>onChange(e.target.value)}>{all && <option value="">{all}</option>}{options.map(v=><option key={v}>{v}</option>)}</select></label>; }
function Dialog({onClose,children}) {
  const ref = useRef(null);
  useEffect(()=>{const previous=document.activeElement; const dialog=ref.current; dialog.showModal(); return ()=>{dialog.close(); previous?.focus();};},[]);
  return createPortal(<dialog className="bugs-dialog" ref={ref} onCancel={onClose} aria-labelledby="report-bug-title" onClick={e=>{if(e.target===e.currentTarget)onClose();}}>{children}</dialog>,document.body);
}
async function readAttachments(files) {
  if(files.length > 4 || files.some(f=>f.size>2*1024*1024)) throw new Error('Choose up to 4 files, each no larger than 2 MB.');
  return Promise.all(files.map(file=>new Promise((resolve,reject)=>{const reader=new FileReader(); reader.onload=()=>resolve({name:file.name,url:reader.result});reader.onerror=()=>reject(new Error('Unable to read this file. Please try again.'));reader.readAsDataURL(file);})));
}
function ReportBug({projects,person,onClose,onCreate}) {
  const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
  async function submit(e) {
    e.preventDefault(); const form=e.currentTarget; const data=new FormData(form);
    if(!String(data.get('title')).trim() || !String(data.get('description')).trim()) {setError('Enter an issue title and description.');return;}
    setBusy(true); setError('');
    try {const attachments=await readAttachments([...form.elements.attachments.files]); const now=new Date();
      onCreate({title:String(data.get('title')).trim(),description:String(data.get('description')).trim(),project:data.get('project'),priority:data.get('priority'),assignedTo:data.get('assignedTo'),steps:data.get('steps').trim(),expected:data.get('expected').trim(),actual:data.get('actual').trim(),reportedBy:person,status:'Open',date:`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`,attachments,comments:[],activity:[{text:`${person} reported this bug.`,at:stamp()}]});
    } catch(err) {setError(err.message); setBusy(false);}
  }
  return <Dialog onClose={onClose}><form onSubmit={submit} className="bugs-report"><header><div><p className="eyebrow">ISSUE TRACKING</p><h2 id="report-bug-title">Report a bug</h2><p>Share enough detail for the team to reproduce the issue.</p></div><button type="button" className="bugs-icon" aria-label="Close report form" onClick={onClose}><X size={21}/></button></header>
    <div className="bugs-form-grid"><label className="bugs-field bugs-wide"><span>Issue title *</span><input autoFocus name="title" required maxLength={140} placeholder="A short, specific summary of the issue"/></label>
    <label className="bugs-field"><span>Project *</span><select name="project" required>{projects.map(p=><option key={p}>{p}</option>)}</select></label>
    <label className="bugs-field"><span>Priority</span><select name="priority" defaultValue="Medium">{PRIORITIES.map(p=><option key={p}>{p}</option>)}</select></label>
    <label className="bugs-field"><span>Assigned to</span><select name="assignedTo">{PEOPLE.map(p=><option key={p}>{p}</option>)}</select></label><label className="bugs-field"><span>Reported by</span><input value={person} readOnly/></label>
    {[['description','Description *','Describe the issue and its impact.'],['steps','Steps to reproduce','1. Open the page\n2. Perform the action\n3. Observe the issue'],['expected','Expected result','What should happen?'],['actual','Actual result','What happens instead?']].map(([name,label,placeholder])=><label className={`bugs-field ${name==='description'||name==='steps'?'bugs-wide':''}`} key={name}><span>{label}</span><textarea name={name} required={name==='description'} rows={3} maxLength={5000} placeholder={placeholder}/></label>)}
    <label className="bugs-field bugs-wide"><span>Attachments</span><input name="attachments" type="file" multiple accept="image/*,.pdf,.txt,.log"/><small>Up to 4 screenshots or documents, 2 MB each.</small></label></div>
    {error && <p role="alert" className="bugs-error">{error}</p>}<footer><button type="button" className="ghost-button" onClick={onClose}>Cancel</button><button className="primary-button" disabled={busy}>{busy?'Adding bug�':'Report bug'}</button></footer>
  </form></Dialog>;
}
export default function OpenBugsPage({projects=[],person='Ekta Singh'}) {
  const [bugs,setBugs,storageError]=useSupportRecords('bugs',person);
  const [filters,setFilters]=useState(EMPTY_FILTERS);const [page,setPage]=useState(1); const [selectedId,setSelectedId]=useState(null); const [reporting,setReporting]=useState(false);const [comment,setComment]=useState('');const [notice,setNotice]=useState('');
  const projectNames=[...new Set([...projects.map(p=>p.name||p.projectName),...bugs.map(b=>b.project)])].filter(Boolean).sort();
  const people=[...new Set([...PEOPLE,person,...bugs.map(b=>b.assignedTo)])];
  const filtered=filterBugs(bugs,filters); const totalPages=Math.max(1,Math.ceil(filtered.length/8)); const currentPage=Math.min(page,totalPages);const visible=filtered.slice((currentPage-1)*8,currentPage*8);
  const selected=bugs.find(b=>b.id===selectedId);
  const changeFilter=(key,value)=>{setFilters(f=>({...f,[key]:value}));setPage(1);};
  function update(field,value) {if(selected[field]===value)return;const labels={status:'status',priority:'priority',assignedTo:'assignee'};setBugs(items=>items.map(b=>b.id===selectedId?{...b,[field]:value,activity:[...b.activity,{text:`${person} changed ${labels[field]} from ${b[field]} to ${value}.`,at:stamp()}]}:b));setNotice(`${labels[field][0].toUpperCase()+labels[field].slice(1)} updated.`);}
  function addComment(e) {e.preventDefault();if(!comment.trim())return;const at=stamp();setBugs(items=>items.map(b=>b.id===selectedId?{...b,comments:[...b.comments,{id:crypto.randomUUID(),author:person,text:comment.trim(),at}],activity:[...b.activity,{text:`${person} added a comment.`,at}]}:b));setComment('');setNotice('Comment added.');}
  const stats=[['Open',Bug,bugs.filter(b=>b.status==='Open').length,'Awaiting triage','status'],['Critical',AlertTriangle,bugs.filter(b=>b.priority==='Critical'&&b.status!=='Resolved').length,'Unresolved bugs','priority'],['High Priority',Flag,bugs.filter(b=>b.priority==='High'&&b.status!=='Resolved').length,'Unresolved bugs','priority'],['In Progress',Clock3,bugs.filter(b=>b.status==='In Progress').length,'Currently being fixed','status'],['Resolved',CircleCheck,bugs.filter(b=>b.status==='Resolved').length,'Ready for verification','status']];
  return <div className="bugs-page"><div className="bugs-notice" role="status">{notice}</div>{storageError&&<p className="bugs-error" role="alert">{storageError}</p>}
    {selected ? <><header className="bugs-heading"><div><button className="bugs-back" onClick={()=>{setSelectedId(null);setComment('');setNotice('');}}><ArrowLeft size={16}/> All bugs</button><p className="eyebrow">{selected.id} / {selected.project}</p><h2>{selected.title}</h2><div className="bugs-inline"><Tag value={selected.priority}/><Tag value={selected.status}/><span>Reported {dateLabel(selected.date)} by {selected.reportedBy}</span></div></div><button className="primary-button" disabled={selected.status==='Resolved'} onClick={()=>update('status','Resolved')}><CircleCheck size={17}/>{selected.status==='Resolved'?'Resolved':'Resolve bug'}</button></header>
    <div className="bugs-detail-grid"><div className="bugs-detail-main"><section className="panel bugs-section"><h3>Bug details</h3>{[['Description',selected.description],['Steps to reproduce',selected.steps],['Expected result',selected.expected],['Actual result',selected.actual]].map(([label,value])=><div className="bugs-prose" key={label}><h4>{label}</h4><p>{value||'Not provided.'}</p></div>)}<h4><Paperclip size={16}/> Attachments <span className="bugs-muted">({selected.attachments.length})</span></h4><div className="bugs-attachments">{selected.attachments.length?selected.attachments.map((a,i)=><a key={i} href={a.url} download={a.name}><Paperclip size={16}/>{a.name}<span>Download</span></a>):<p className="bugs-muted">No attachments added.</p>}</div></section>
    <section className="panel bugs-section"><h3><MessageSquare size={18}/> Comments ({selected.comments.length})</h3>{selected.comments.length?selected.comments.map(c=><article className="bugs-comment" key={c.id}><div><strong>{c.author}</strong><time>{dateLabel(c.at)}</time></div><p>{c.text}</p></article>):<p className="bugs-muted">No comments yet. Add findings or a progress update.</p>}<form onSubmit={addComment}><label className="bugs-field"><span>Add a comment</span><textarea value={comment} onChange={e=>setComment(e.target.value)} maxLength={3000} rows={3} placeholder="Share an update with the team�"/></label><button className="primary-button" disabled={!comment.trim()}>Add comment</button></form></section></div>
    <aside><section className="panel bugs-section"><h3>Manage bug</h3><Select label="Assigned to" value={selected.assignedTo} onChange={v=>update('assignedTo',v)} options={people}/><Select label="Priority" value={selected.priority} onChange={v=>update('priority',v)} options={PRIORITIES}/><Select label="Status" value={selected.status} onChange={v=>update('status',v)} options={STATUSES}/></section><section className="panel bugs-section"><h3><History size={18}/> Activity history</h3><ol className="bugs-activity">{[...selected.activity].reverse().map((a,i)=><li key={i}><p>{a.text}</p><time>{dateLabel(a.at)} � {new Date(a.at).toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit'})}</time></li>)}</ol></section></aside></div></> : <>
    <header className="bugs-heading"><div><p className="eyebrow">ISSUE TRACKING</p><h2>Open Bugs</h2><p>Track issues, set priorities, and keep project delivery on course.</p></div><button className="primary-button" onClick={()=>setReporting(true)}><Plus size={18}/> Report Bug</button></header>
    <div className="bugs-summary">{stats.map(([label,Icon,count,hint])=><article className={`panel bugs-stat bugs-stat-${token(label)}`} key={label}><div><span>{label}</span><Icon size={19}/></div><strong>{count}</strong><small>{hint}</small></article>)}</div>
    <section className="panel bugs-list-panel"><div className="bugs-list-heading"><div><h3>Bug register <span className="bugs-count">{bugs.length}</span></h3><p>All reported issues across your projects</p></div><span className="bugs-demo">Demo � Saved in this browser</span></div>
    <div className="bugs-filters"><label className="bugs-search"><Search size={18}/><input aria-label="Search bugs" value={filters.search} onChange={e=>changeFilter('search',e.target.value)} placeholder="Search bug ID, issue, project or person�"/></label><div className="bugs-filter-grid"><Select label="Status" value={filters.status} onChange={v=>changeFilter('status',v)} options={STATUSES} all="All statuses"/><Select label="Priority" value={filters.priority} onChange={v=>changeFilter('priority',v)} options={PRIORITIES} all="All priorities"/><Select label="Project" value={filters.project} onChange={v=>changeFilter('project',v)} options={projectNames} all="All projects"/><Select label="Assigned to" value={filters.assignedTo} onChange={v=>changeFilter('assignedTo',v)} options={people} all="Anyone"/><label className="bugs-field"><span>Reported date</span><input aria-label="Reported date" type="date" value={filters.date} onChange={e=>changeFilter('date',e.target.value)}/></label><button className="bugs-reset" onClick={()=>{setFilters(EMPTY_FILTERS);setPage(1);}}>Clear filters</button></div></div>
    <div className="bugs-table-wrap"><table className="bugs-table"><thead><tr>{['Bug ID','Issue','Project','Priority','Assigned To','Reported By','Date','Status','Action'].map(h=><th key={h} scope="col">{h}</th>)}</tr></thead><tbody>{visible.map(b=><tr key={b.id}><td className="bugs-id">{b.id}</td><td className="bugs-issue"><button onClick={()=>{setSelectedId(b.id);setNotice('');}}>{b.title}</button></td><td>{b.project}</td><td><Tag value={b.priority}/></td><td>{b.assignedTo}</td><td>{b.reportedBy}</td><td className="bugs-date">{dateLabel(b.date)}</td><td><Tag value={b.status}/></td><td><button className="bugs-view" aria-label={`View ${b.id}`} onClick={()=>{setSelectedId(b.id);setNotice('');}}>View</button></td></tr>)}</tbody></table>{!visible.length&&<div className="bugs-empty"><Search size={28}/><h3>No bugs match your filters</h3><p>Try a different keyword or clear your filters.</p><button className="ghost-button" onClick={()=>{setFilters(EMPTY_FILTERS);setPage(1);}}>Clear filters</button></div>}</div>
    <footer className="bugs-pagination"><span>{filtered.length?`${(currentPage-1)*8+1}�${Math.min(currentPage*8,filtered.length)}`:'0'} of {filtered.length} bugs</span><nav aria-label="Bug pages"><button aria-label="Previous page" disabled={currentPage===1} onClick={()=>setPage(currentPage-1)}><ChevronLeft size={17}/></button><span>Page {currentPage} of {totalPages}</span><button aria-label="Next page" disabled={currentPage===totalPages} onClick={()=>setPage(currentPage+1)}><ChevronRight size={17}/></button></nav></footer></section></>}
    {reporting&&<ReportBug projects={projectNames} person={person} onClose={()=>setReporting(false)} onCreate={bug=>{const next=Math.max(1042,...bugs.map(b=>Number(b.id.replace('BUG-',''))||0))+1;const record={...bug,id:`BUG-${next}`};setBugs(current=>[record,...current]);setReporting(false);setSelectedId(record.id);setNotice(`${record.id} reported successfully.`);}}/>}
  </div>;
}
