import { workloadLabel } from './workload.js';
﻿import React, { useCallback, useState } from 'react';
import { AlertTriangle } from 'lucide-react';
import { useTeamState } from './teamStore.js';
import { dateLabel, projectProgress, TEAM_ROLES } from './teamData.js';
import { Avatar, Person, Pill, Progress, Page, TableCard, SearchField, Select, Empty, Drawer, Toast } from './TeamComponents.jsx';
function AssignmentForm({ project, state, onClose, onSaved }) {
  const [form, setForm] = useState(() => ({ team: project.team.map(item => ({ ...item })), startDate: project.startDate, dueDate: project.dueDate, priority: project.priority, notes: project.notes }));
  const [error, setError] = useState('');
  const update = (key, value) => { setForm(current => ({ ...current, [key]: value })); setError(''); };
  function toggle(member, checked) { update('team', checked ? [...form.team, { memberId: member.id, role: TEAM_ROLES.includes(member.role) ? member.role : 'Developer' }] : form.team.filter(item => item.memberId !== member.id)); }
  function submit(event) { event.preventDefault(); try { state.saveAssignment(project.id, form); onSaved(`Team assignment saved for ${project.name}.`); } catch (err) { setError(err.message); } }
  return <Drawer title="Assign / Manage team" subtitle={project.name} onClose={onClose}><form onSubmit={submit}><fieldset className="tm-members"><legend>Team members *</legend><p>Select one or more members and choose their project role.</p>{state.members.map(member => { const selected = form.team.find(item => item.memberId === member.id); return <div className="tm-member-option" key={member.id}><label><input type="checkbox" checked={!!selected} onChange={event => toggle(member, event.target.checked)}/><Person member={member}/><span className={member.workload > 85 ? 'tm-warning-text' : ''}>{workloadLabel(member.workload)}%</span></label>{member.workload > 85 && <small className="tm-warning-text"><AlertTriangle size={13}/> Workload above 85% — check capacity before assigning.</small>}{selected && <label className="tm-field"><span>Project role for {member.name}</span><select value={selected.role} onChange={event => update('team', form.team.map(item => item.memberId === member.id ? { ...item, role: event.target.value } : item))}>{TEAM_ROLES.map(role => <option key={role}>{role}</option>)}</select></label>}</div>; })}</fieldset><div className="tm-form-grid"><label className="tm-field"><span>Start date</span><input type="date" value={form.startDate} onChange={event => update('startDate', event.target.value)}/></label><label className="tm-field"><span>Due date *</span><input required type="date" min={form.startDate || undefined} value={form.dueDate} onChange={event => update('dueDate', event.target.value)}/></label><label className="tm-field"><span>Priority</span><select value={form.priority} onChange={event => update('priority', event.target.value)}>{['Low','Medium','High','Critical','Urgent'].map(value => <option key={value}>{value}</option>)}</select></label><label className="tm-field tm-wide"><span>Notes</span><textarea rows={4} maxLength={2000} value={form.notes} onChange={event => update('notes', event.target.value)} placeholder="Responsibilities, handover details, or delivery notes..."/></label></div>{error && <p className="tm-error" role="alert">{error}</p>}<footer className="tm-form-actions"><button type="button" className="ghost-button" onClick={onClose}>Cancel</button><button type="submit" className="primary-button">Save assignment</button></footer></form></Drawer>;
}
export default function AssignProjects() {
  const state = useTeamState(); const [filters, setFilters] = useState({ search: '', status: '', priority: '', client: '', date: '' }); const [selected, setSelected] = useState(null); const [message, setMessage] = useState('');
  const closeToast = useCallback(() => setMessage(''), []);
  const change = (key, value) => setFilters(current => ({ ...current, [key]: value }));
  const reset = () => setFilters({ search: '', status: '', priority: '', client: '', date: '' });
  const rows = state.projects.filter(project => `${project.name} ${project.client}`.toLowerCase().includes(filters.search.trim().toLowerCase()) && (!filters.status || project.status === filters.status) && (!filters.priority || project.priority === filters.priority) && (!filters.client || project.client === filters.client) && (!filters.date || project.dueDate === filters.date));
  return <Page title="Assign Projects" description="Build the right team for every project and keep responsibilities clear."><TableCard title="Project assignments" count={rows.length} filters={<><SearchField value={filters.search} onChange={value => change('search', value)} placeholder="Search projects or clients..."/><div className="tm-filter-row"><Select label="Status" value={filters.status} onChange={value => change('status', value)} options={['Open','Active','In Progress','Completed']} all="All statuses"/><Select label="Priority" value={filters.priority} onChange={value => change('priority', value)} options={['Low','Medium','High','Critical','Urgent']} all="All priorities"/><Select label="Client" value={filters.client} onChange={value => change('client', value)} options={[...new Set(state.projects.map(project => project.client))]} all="All clients"/><label className="tm-field"><span>Deadline</span><input type="date" value={filters.date} onChange={event => change('date', event.target.value)}/></label><button className="tm-reset" onClick={reset}>Reset filters</button></div></>}>{rows.length ? <div className="tm-table-wrap"><table className="tm-table"><thead><tr>{['Project','Client','Priority','Deadline','Assigned team','Progress','Status','Action'].map(label => <th scope="col" key={label}>{label}</th>)}</tr></thead><tbody>{rows.map(project => <tr key={project.id}><td className="tm-project-names"><strong>{project.name}</strong></td><td>{project.client}</td><td><Pill value={project.priority}/></td><td className="tm-nowrap">{dateLabel(project.dueDate)}</td><td>{project.team.length ? <div className="tm-stack">{project.team.map(item => <Avatar key={item.memberId} member={state.members.find(member => member.id === item.memberId)}/>)}</div> : <span>Unassigned</span>}</td><td><Progress value={projectProgress(state, project.id)} label={`${project.name} progress`}/></td><td><Pill value={project.status}/></td><td><button className="tm-view" onClick={() => setSelected(project.id)} aria-label={`Assign or manage ${project.name}`}>{project.team.length ? 'Manage' : 'Assign'}</button></td></tr>)}</tbody></table></div> : <Empty onReset={reset}/>}</TableCard>{selected && <AssignmentForm project={state.projects.find(project => project.id === selected)} state={state} onClose={() => setSelected(null)} onSaved={text => { setSelected(null); setMessage(text); }}/>}<Toast message={message} onClose={closeToast}/></Page>;
}
