import React, { useState } from 'react';
import { Users, ClipboardList, AlertTriangle, CircleCheck } from 'lucide-react';
import { useTeamState } from './teamStore.js';
import { dateLabel, memberStats, teamSummary } from './teamData.js';
import { Page, TableCard, Person, Pill, Progress, SearchField, Select, Empty, Drawer } from './TeamComponents.jsx';
export default function TeamProgress() {
  const state = useTeamState(); const [search, setSearch] = useState(''); const [status, setStatus] = useState(''); const [selected, setSelected] = useState(null);
  const reset = () => { setSearch(''); setStatus(''); };
  const rows = state.members.map(member => ({ member, stats: memberStats(state, member) })).filter(({ member, stats }) => member.name.toLowerCase().includes(search.trim().toLowerCase()) && (!status || stats.status === status));
  const member = state.members.find(item => item.id === selected); const details = member ? memberStats(state, member) : null;
  const totals = teamSummary(state); const icons = [Users, ClipboardList, AlertTriangle, CircleCheck];
  return <Page title="Team Progress" description="Track delivery health and spot where your team needs support."><div className="tm-summary">{['Total Members','Active Tasks','Overdue Tasks','Completed This Week'].map((label, index) => { const Icon = icons[index]; return <section className="panel tm-stat" key={label}><div><span>{label}</span><Icon size={19}/></div><strong>{totals[index]}</strong><small>{index === 3 ? '28–29 Sept 2026' : index === 2 ? 'Open tasks past their due date' : 'Across the mock team'}</small></section>; })}</div><TableCard title="Member progress" count={rows.length} filters={<><SearchField value={search} onChange={setSearch}/><div className="tm-filter-row"><Select label="Status" value={status} onChange={setStatus} options={['On Track','At Risk','Delayed']} all="All statuses"/><button className="tm-reset" onClick={reset}>Reset filters</button></div></>}>{rows.length ? <div className="tm-table-wrap"><table className="tm-table"><thead><tr>{['Member','Projects','Tasks assigned / done','Progress','Last update','Status','Action'].map(label => <th scope="col" key={label}>{label}</th>)}</tr></thead><tbody>{rows.map(({ member, stats }) => <tr key={member.id}><td><Person member={member}/></td><td className="tm-project-names">{stats.projects.map(project => project.name).join(', ') || 'No projects assigned'}</td><td>{stats.tasks.length} / {stats.done}</td><td><Progress value={stats.progress} label={`${member.name} task progress`}/></td><td className="tm-nowrap">{dateLabel(stats.lastUpdate)}</td><td><Pill value={stats.status}/></td><td><button className="tm-view" aria-label={`View ${member.name} progress`} onClick={() => setSelected(member.id)}>View</button></td></tr>)}</tbody></table></div> : <Empty onReset={reset}/>}</TableCard>{member && <Drawer title={member.name} subtitle={`${member.role} · Progress overview`} onClose={() => setSelected(null)}><div className="tm-detail-facts"><div><span>Hours logged</span><strong>{member.hours}h</strong></div><div><span>Open bugs</span><strong>{member.openBugs.length}</strong></div><div><span>Delivery status</span><Pill value={details.status}/></div></div><h3>Assigned tasks</h3>{details.tasks.length ? <ul className="tm-detail-list">{details.tasks.map(task => <li key={task.id}><strong>{task.title}</strong><p>{state.projects.find(project => project.id === task.projectId)?.name}</p><div><span>Due {dateLabel(task.dueDate)}</span><Pill value={task.status}/></div></li>)}</ul> : <p className="tm-muted">No tasks assigned yet.</p>}<h3>Open bugs</h3>{member.openBugs.length ? <ul className="tm-detail-list">{member.openBugs.map(bug => <li key={bug.id}><strong>{bug.title}</strong><div><span>{bug.id}</span><Pill value={bug.priority}/></div></li>)}</ul> : <p className="tm-muted">No open bugs assigned to this member.</p>}</Drawer>}</Page>;
}
