import mongoose from "mongoose";

const leadSchema = new mongoose.Schema({
  id: { type: String, required: true, unique: true },
  name: { type: String, required: true },
  phone: { type: String, required: true },
  email: { type: String, default: "" },
  alternatePhone: { type: String, default: "" },
  city: { type: String, default: "" },
  state: { type: String, default: "" },
  qualification: { type: String, default: "" },
  college: { type: String, default: "" },
  company: { type: String, default: "" },
  type: { type: String, default: "Training" },
  interest: { type: String, default: "" },
  courseInterest: { type: String, default: "" },
  programInterest: { type: String, default: "" },
  programType: { type: String, default: "Training" },
  internshipInterest: { type: String, default: "Need Details" },
  callStatus: { type: String, default: "Pending" },
  interestStatus: { type: String, default: "Not Contacted" },
  followUpDate: { type: String, default: "" },
  followUpTime: { type: String, default: "" },
  remark: { type: String, default: "" },
  active: { type: Boolean, default: true },
  snoozed: { type: Boolean, default: false },
  source: { type: String, default: "Website" },
  leadSource: { type: String, default: "Website" },
  assignedTo: { type: mongoose.Schema.Types.Mixed, default: "" },
  assignedDate: { type: String, default: "" },
  status: { type: String, default: "Pending" },
  value: { type: Number, default: 0 },
  notes: { type: String, default: "" },
  createdAt: { type: String, default: () => new Date().toISOString().slice(0, 10) },
}, { timestamps: true });

export default mongoose.model("Lead", leadSchema);